### ISSUE TITLE
Example to integrate Sentry

### ISSUE THREAD

**Issue by rohanag108** [izumin5210/grapi#144]
Hi @izumin5210 can you give an example of how to integrate and use sentry with the api server?. 

I am able to capture errors using the instructions mentioned here:
https://docs.sentry.io/clients/go/

However capturing panics seems to be difficult since if you get a panic in one of the handlers the server crashes and there is no recovery other than restarting the process?

please advise.

**Comment by izumin5210** [comment]
We implement servers  as gRPC server in grapi project.
So we can set middlewares using [`grpc#UnaryServerInterceptor`](https://godoc.org/google.golang.org/grpc#UnaryServerInterceptor)

And [grpc-ecossytem/go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware) may help you ✌️

**Comment by rohanag108** [comment]
Yeah looks like that will work. Thanks @izumin5210 !
