### ISSUE TITLE
Limit on Concurrent HTTP connections?

### ISSUE THREAD

**Issue by rohanag108** [izumin5210/grapi#148]
Is there a limit on the number of concurrent HTTP connections?. I see that the requests get timed out if there are more than 1000 connections. Is this a config set somewhere which we can tweak?

**Comment by izumin5210** [comment]
you set [`grpc.MaxConcurrentStreams`](https://godoc.org/google.golang.org/grpc#MaxConcurrentStreams) to [`grapiserver.WithGrpcServerOptions`](https://godoc.org/github.com/izumin5210/grapi/pkg/grapiserver#WithGrpcServerOptions), you can tweak it 😄
