### ISSUE TITLE
window grapi  Filename too long

### ISSUE THREAD

**Issue by gyf19** [izumin5210/grapi#61]
grouped write of manifest, lock and vendor: error while writing out vendor tree:
 failed to write dep tree: failed to export github.com/izumin5210/grapi: error:
unable to create file C:\Users\ADMINI~1\AppData\Local\Temp\dep227690330\vendor\g
ithub.com\izumin5210\grapi\pkg/grapicmd/internal/module/generator/.snapshots/Tes
t_ServiceGenerator-foo-bar-baz_with_list,create,rename,delete,move_move-Generate
-app-server-foo-bar_baz_server_register_funcs.go: Filename too long
: exit status 128
failed to execute `dep ensure`: exit status 1         

![image](https://user-images.githubusercontent.com/233857/38969927-3dd3f826-43c5-11e8-869f-aba80c42a7fb.png)

**Comment by izumin5210** [comment]
@gyf19 Sorry for the late response :bow:

Could you try this?
https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows
